// next/src/components/parts/date-field.tsx
"use client";

import CalendarMonthIcon from "@mui/icons-material/CalendarMonth";
import { Box, BoxProps, ClickAwayListener, IconButton, Paper, Popper, TextField, TextFieldProps } from "@mui/material";
import { DateCalendar, LocalizationProvider } from "@mui/x-date-pickers";
import { AdapterDateFns } from "@mui/x-date-pickers/AdapterDateFns";
import { PickerSelectionState } from "@mui/x-date-pickers/internals";
import { enUS, ja } from "date-fns/locale";
import { useAtomValue } from "jotai";
import { ChangeEventHandler, memo, useCallback, useEffect, useMemo, useRef, useState } from "react";

import Config, { NecessaryValue } from "@/app.config";
import { labelsAtom } from "@/composables/label";
import { languageAtom } from "@/composables/language";
import useNecessary from "@/composables/necessary";

/** 日付フィールドプロパティ型 */
export type DateFieldProps = Omit<TextFieldProps, "onChange" | "sx" | "value"> & {
  errorMessage?: string;
  necessary?: boolean | NecessaryValue;
  onChange?: (value: string) => void;
  readonly?: boolean;
  sx?: BoxProps["sx"];
  textFieldSx?: { sx: TextFieldProps["sx"] };
  value?: string;
};

/** 日付文字列の不正検出する正規表現パターン */
const invalidPattern = new RegExp(String.raw`[^${Config.dateDelimiters}\d\s]`);

/** 日付文字列を年、月、日に分割する正規表現パターン */
const splitPattern = new RegExp(String.raw`[${Config.dateDelimiters}]`);

/** 文字列 or 配列から数値化した年月日配列を取得 */
const extractYMD = (value: string | string[]): [number, number, number] => {
  const aValue = typeof value === "string" ? value : value.length === 1 ? value[0] : null;
  return aValue
    ? [Number(aValue.slice(0, -4)) || 0, Number(aValue.slice(-4, -2)) || 0, Number(aValue.slice(-2)) || 0]
    : [Number(value[2]) || 0, Number(value[1]) || 0, Number(value[0]) || 0];
};

/** 年月日配列の値がゼロの要素を当日[年,月,日]要素で置換 */
const adjustYMD = (ymd: [number, number, number]): [number, number, number] => {
  const today = new Date();
  return [
    ymd[0] === 0 ? today.getFullYear() : ymd[0] + (1000 <= ymd[0] ? 0 : 2000),
    ymd[1] === 0 ? today.getMonth() + 1 : ymd[1],
    ymd[2] === 0 ? today.getDate() : ymd[2],
  ];
};

/** 年月日配列で示される日付が暦日に存在するか確認 */
const validateYMD = (ymd: [number, number, number]) => {
  const date = new Date(ymd[0], ymd[1] - 1, ymd[2], 0, 0, 0, 0);
  return date.getMonth() === ymd[1] - 1 && date.getDate() === ymd[2];
};

/** 年月日配列を日付文字列に変換 */
const toStringYMD = (ymd: [number, number, number], delimiter = "") => {
  return `${ymd[0].toString()}${delimiter}${ymd[1].toString().padStart(2, "0")}${delimiter}${ymd[2].toString().padStart(2, "0")}`;
};

/** 日付テキストボックス */
function DateField({ disabled, errorMessage, necessary, onChange, readonly, sx, textFieldSx, value, ...restProps }: DateFieldProps) {
  const [focus, setFocus] = useState(false);

  const labels = useAtomValue(labelsAtom);
  const [show, required] = useNecessary(necessary);

  const editing = useMemo(() => !readonly && !disabled && show && focus, [readonly, disabled, show, focus]);

  const [showValue, setShowValue] = useState("");
  const [showValid, setShowValid] = useState(true);

  const [editValue, setEditValue] = useState("");
  const editValid = useMemo(() => (!required && !editValue) || (!!editValue && validateYMD(adjustYMD(extractYMD(editValue)))), [required, editValue]);

  const currentValue = useMemo(() => (editing ? editValue : showValue), [editing, editValue, showValue]);
  const currentValid = useMemo(() => (editing ? editValid : showValid), [editing, editValid, showValid]);

  const error = useMemo(() => (!currentValid || !!errorMessage) && !readonly, [currentValid, errorMessage, readonly]);
  const message = useMemo(() => {
    let value = "";
    if (currentValid) {
      value = errorMessage ? `${Config.errorMark}${errorMessage}` : " ";
    } else {
      value = required ? `${Config.errorMark}${labels.long.required} YYYYMMDD` : "YYYYMMDD";
    }
    return readonly ? " " : value;
  }, [currentValid, errorMessage, labels, readonly, required]);

  const changeHandler: ChangeEventHandler<HTMLInputElement | HTMLTextAreaElement> = useCallback((e) => {
    setEditValue(e.target.value.replace(/\D/g, ""));
  }, []);

  const focusHandler = (focusValue: boolean) => {
    if (readonly || disabled) {
      return;
    }

    setFocus(focusValue);
    if (focusValue) {
      return;
    }

    let workShowValid = !required;
    let workShowValue = "";
    let workEditValue = "";
    if (editValid && editValue) {
      const ymd = adjustYMD(extractYMD(editValue));
      workShowValid = true;
      workShowValue = toStringYMD(ymd, Config.dateDelimiter);
      workEditValue = toStringYMD(ymd);
    }
    setShowValid(workShowValid);
    setShowValue(workShowValue);
    setEditValue(workEditValue);

    onChange?.(workShowValue);
  };

  useEffect(() => {
    const normalizedValue = value?.trim() ?? "";
    let workShowValid = false;
    const workShowValue = normalizedValue;
    let workEditValue = "";
    try {
      if (!normalizedValue) {
        workShowValid = !required;
        return;
      }
      if (invalidPattern.test(normalizedValue)) {
        return;
      }
      const elements = normalizedValue.replace(/\s/g, "").split(splitPattern).reverse();
      if (3 < elements.length) {
        return;
      }
      const ymd = adjustYMD(extractYMD(elements));
      if (!validateYMD(ymd)) {
        return;
      }
      workShowValid = true;
      workEditValue = toStringYMD(ymd);
    } finally {
      setShowValid(workShowValid);
      setShowValue(workShowValue);
      setEditValue(workEditValue);
    }
  }, [required, value]);

  // Calendar Date Picker
  const language = useAtomValue(languageAtom);

  // TODO: 英語、日本語以外の言語対応
  const locale = useMemo(() => (language == "en" ? enUS : ja), [language]);

  const anchorEl = useRef<HTMLButtonElement>(null);
  const [openCalendar, setOpenCalendar] = useState(false);

  const calendarValue = useMemo(() => {
    const ymd = adjustYMD(extractYMD(editValue));
    return editValid ? new Date(ymd[0], ymd[1] - 1, ymd[2], 0, 0, 0, 0) : new Date();
  }, [editValid, editValue]);

  const selectHandler = useCallback(
    (value: Date | null, state: PickerSelectionState | undefined) => {
      if (state !== "finish") {
        return;
      }
      if (value) {
        const ymd: [number, number, number] = [value.getFullYear(), value.getMonth() + 1, value.getDate()];
        onChange?.(toStringYMD(ymd, Config.dateDelimiter));
      }
      setOpenCalendar(false);
    },
    [onChange]
  );

  if (!show) return null;
  return (
    <>
      <Box sx={{ display: "flex", flexDirection: "row", ...sx }}>
        <TextField
          disabled={disabled ?? false}
          error={error}
          FormHelperTextProps={{ sx: { paddingLeft: "1em" } }}
          helperText={message}
          InputLabelProps={{ required: false, shrink: true }}
          inputProps={{ maxLength: 8, readOnly: readonly ?? false }}
          onBlur={() => focusHandler(false)}
          onFocus={() => focusHandler(true)}
          onChange={changeHandler}
          required={required}
          sx={{ flexGrow: 1, flexShrink: 1, ...textFieldSx }}
          value={currentValue}
          variant="standard"
          {...restProps}
        ></TextField>
        <IconButton
          disabled={(disabled || readonly) ?? false}
          ref={anchorEl}
          sx={{ flexGrow: 0, flexShrink: 0 }}
          onClick={() => setOpenCalendar(!openCalendar)}
        >
          <CalendarMonthIcon />
        </IconButton>
      </Box>
      <Popper anchorEl={anchorEl.current} open={openCalendar} sx={{ zIndex: (theme) => theme.zIndex.drawer + 3 }}>
        <ClickAwayListener onClickAway={() => setOpenCalendar(false)}>
          <Paper elevation={20}>
            <LocalizationProvider dateAdapter={AdapterDateFns} adapterLocale={locale}>
              <DateCalendar onChange={selectHandler} value={calendarValue} />
            </LocalizationProvider>
          </Paper>
        </ClickAwayListener>
      </Popper>
    </>
  );
}
export default memo(DateField);

// nuxt/components/date-field.vue
<!-- 日付テキストボックス -->

<script setup lang="ts">
import { mdiCalendar } from "@mdi/js";
import Datepicker from "@vuepic/vue-datepicker";
import "@vuepic/vue-datepicker/dist/main.css";

defineOptions({
  inheritAttrs: false,
});

interface Props {
  modelValue: string | null;
  necessary: string;
  readonly?: boolean | undefined;
  disabled?: boolean | undefined;
  errorMessage?: string | undefined;
}
const props = defineProps<Props>();

interface Emits {
  (e: "update:modelValue", value: string | null): void;
}
const emits = defineEmits<Emits>();

const config = useAppConfig();
const { labels } = useLabel();

const invalidPattern = new RegExp(String.raw`[^${config.dateDelimiters}\d\s]`);
const splitPattern = new RegExp(String.raw`[${config.dateDelimiters}]`);

const show = computed(() => props.necessary !== config.necessary.notNeeded);
const required = computed(() => props.necessary === config.necessary.required);
const message = computed(() => {
  let value = "";
  if (currentValid.value) {
    value = props.errorMessage ? `${config.errorMark}${props.errorMessage}` : "";
  } else {
    value = required.value ? `${config.errorMark}${labels.value.long.required} YYYYMMDD` : "YYYYMMDD";
  }
  return value;
});

const focus = ref(false);
const editing = computed(() => !props.readonly && !props.disabled && show.value && focus.value);

const showValid = ref(false);
const showValue = ref("");

const editValid = computed(() => (!required.value && !editValue.value) || (!!editValue.value && validateYMD(adjustYMD(extractYMD(editValue.value)))));
const editValue = ref("");

const currentValid = computed(() => (editing.value ? editValid.value : showValid.value));
const currentValue = computed({
  get: () => (editing.value ? editValue.value : showValue.value),
  set: (value) => (editValue.value = value),
});

onMounted(() => {
  const stop = watch(
    props,
    (propsValue) => {
      const normalizedValue = propsValue.modelValue?.trim() ?? "";
      showValid.value = false;
      showValue.value = normalizedValue;
      editValue.value = "";
      if (!normalizedValue) {
        showValid.value = !required.value;
        return;
      }
      if (invalidPattern.test(normalizedValue)) {
        return;
      }
      const elements = normalizedValue.replace(/\s/g, "").split(splitPattern).reverse();
      if (3 < elements.length) {
        return;
      }
      const ymd = adjustYMD(extractYMD(elements));
      if (!validateYMD(ymd)) {
        return;
      }
      showValid.value = true;
      editValue.value = toStringYMD(ymd);
    },
    {
      immediate: true,
      deep: false,
    }
  );
  onScopeDispose(stop);
});

const extractYMD = (value: string | string[]): [number, number, number] => {
  const aValue = typeof value === "string" ? value : value.length === 1 ? value[0] : null;
  return aValue
    ? [Number(aValue.slice(0, -4)) || 0, Number(aValue.slice(-4, -2)) || 0, Number(aValue.slice(-2)) || 0]
    : [Number(value[2]) || 0, Number(value[1]) || 0, Number(value[0]) || 0];
};

const adjustYMD = (ymd: [number, number, number]): [number, number, number] => {
  const today = new Date();
  return [
    ymd[0] === 0 ? today.getFullYear() : ymd[0] + (1000 <= ymd[0] ? 0 : 2000),
    ymd[1] === 0 ? today.getMonth() + 1 : ymd[1],
    ymd[2] === 0 ? today.getDate() : ymd[2],
  ];
};

const validateYMD = (ymd: [number, number, number]) => {
  const date = new Date(ymd[0], ymd[1] - 1, ymd[2], 0, 0, 0, 0);
  return date.getMonth() === ymd[1] - 1 && date.getDate() === ymd[2];
};

const toStringYMD = (ymd: [number, number, number], delimiter = "") =>
  `${ymd[0].toString()}${delimiter}${ymd[1].toString().padStart(2, "0")}${delimiter}${ymd[2].toString().padStart(2, "0")}`;

const inputHandler = (e: Event) => {
  const element = e.target as HTMLInputElement;
  element.value = element.value.replace(/\D/g, "");
  currentValue.value = element.value;
};

const focusHandler = (value: boolean) => {
  if (props.readonly || props.disabled) {
    return;
  }
  focus.value = value;
  if (value) {
    return;
  }
  if (editValid.value) {
    showValid.value = true;
    showValue.value = "";
    if (editValue.value) {
      const ymd = adjustYMD(extractYMD(editValue.value));
      showValue.value = toStringYMD(ymd, config.dateDelimiter);
      editValue.value = toStringYMD(ymd);
    }
  } else {
    showValid.value = !required.value;
    showValue.value = "";
    editValue.value = "";
  }
  emits("update:modelValue", showValue.value === "" ? null : showValue.value);
};

// Date Picker

const { primaryLanguage } = useAcceptLanguage();

const menu = ref(false);
const showMenu = computed({
  get: () => menu.value,
  set: (value) => {
    menu.value = value;
    if (value) {
      calendarValue.value = editValid.value ? toStringYMD(adjustYMD(extractYMD(editValue.value))) : "";
    }
  },
});

const calendarValue = ref("");

const selectHandler = (value: string) => {
  calendarValue.value = value;
  showValid.value = true;
  showValue.value = toStringYMD(adjustYMD(extractYMD(value)), config.dateDelimiter);
  editValue.value = value;
  showMenu.value = false;
  focusHandler(false);
};
</script>

<template>
  <v-text-field
    maxlength="8"
    v-bind="$attrs"
    v-show="show"
    :disabled="props.disabled"
    :error-messages="message"
    :readonly="props.readonly"
    :value="currentValue"
    @input="inputHandler"
    @update:focused="focusHandler"
  >
    <template #message="{ message:msg }">
      <span style="padding-left: 1em;">{{ msg }}</span>
    </template>
    <template v-if="!props.disabled && !props.readonly" #append>
      <v-menu v-model="showMenu">
        <template #activator="{ props:activatorProps }">
          <v-btn class="rounded-circle" color="grey" size="small" variant="text" v-bind="activatorProps" :icon="mdiCalendar" />
        </template>
        <datepicker
          auto-apply
          inline
          model-type="yyyyMMdd"
          v-model="calendarValue"
          :action-row="{ showSelect: false, showCancel: false, showNow: false, showPreview: false }"
          :hide-navigation="['time']"
          :locale="primaryLanguage"
          @update:model-value="selectHandler"
        />
      </v-menu>
    </template>
  </v-text-field>
</template>
