// next/src/components/parts/time-field.tsx
"use client";

import { TextField, TextFieldProps } from "@mui/material";
import { useAtomValue } from "jotai";
import { ChangeEventHandler, memo, useCallback, useEffect, useMemo, useState } from "react";

import Config, { NecessaryValue } from "@/app.config";
import { labelsAtom } from "@/composables/label";
import useNecessary from "@/composables/necessary";

/** 時刻フィールドプロパティ型 */
export type TimeFieldProps = Omit<TextFieldProps, "onChange" | "value"> & {
  errorMessage?: string;
  necessary?: boolean | NecessaryValue;
  onChange?: (value: string) => void;
  readonly?: boolean;
  value?: string;
};

/** 入力可能最大時 */
const maxHour = Number(Config.maxTime.hour) || 0;

/** 入力可能最大分 */
const maxMinute = Number(Config.maxTime.minute) || 0;

/** 時刻文字列の不正検出する正規表現パターン */
const invalidPattern = new RegExp(String.raw`[^${Config.timeDelimiter}\d\s]`);

/** 文字列 or 配列から数値化した時分配列を取得 */
const extractHM = (value: string | string[]): [number, number] => {
  const aValue = typeof value === "string" ? value : value.length === 1 ? value[0] : null;
  return aValue ? [Number(aValue.slice(0, -2)) || 0, Number(aValue.slice(-2)) || 0] : [Number(value[1]) || 0, Number(value[0]) || 0];
};

/** 時分配列で示される時刻の検証 */
const validateHM = (hm: [number, number]) => {
  return 0 <= hm[0] && hm[0] <= maxHour && 0 <= hm[1] && hm[1] <= maxMinute;
};

/** 時分配列を時刻文字列に変換 */
const toStringHM = (hm: [number, number], delimiter: string = "") => `${hm[0].toString().padStart(2, "0")}${delimiter}${hm[1].toString().padStart(2, "0")}`;

/** 時刻テキストボックス */
function TimeField({ disabled, errorMessage, necessary, onChange, readonly, value, ...restProps }: TimeFieldProps) {
  const [focus, setFocus] = useState(false);

  const labels = useAtomValue(labelsAtom);
  const [show, required] = useNecessary(necessary);

  const editing = useMemo(() => !readonly && !disabled && show && focus, [readonly, disabled, show, focus]);

  const [showValue, setShowValue] = useState("");
  const [showValid, setShowValid] = useState(true);

  const [editValue, setEditValue] = useState("");
  const editValid = useMemo(() => (!required && !editValue) || (!!editValue && validateHM(extractHM(editValue))), [required, editValue]);

  const currentValue = useMemo(() => (editing ? editValue : showValue), [editing, editValue, showValue]);
  const currentValid = useMemo(() => (editing ? editValid : showValid), [editing, editValid, showValid]);

  const error = useMemo(() => (!currentValid || !!errorMessage) && !readonly, [currentValid, errorMessage, readonly]);
  const message = useMemo(() => {
    let value = "";
    if (currentValid) {
      value = errorMessage ? `${Config.errorMark}${errorMessage}` : " ";
    } else {
      const timeNote = `00${Config.timeDelimiter}00～${Config.maxTime.hour}${Config.timeDelimiter}${Config.maxTime.minute}`;
      value = required ? `${Config.errorMark}${labels.long.required} ${timeNote}` : timeNote;
    }
    return readonly ? " " : value;
  }, [currentValid, errorMessage, labels, readonly, required]);

  const changeHandler: ChangeEventHandler<HTMLInputElement | HTMLTextAreaElement> = useCallback((e) => {
    setEditValue(e.target.value.replace(/\D/g, ""));
  }, []);

  const focusHandler = (focusValue: boolean) => {
    if (readonly || disabled) {
      return;
    }

    setFocus(focusValue);
    if (focusValue) {
      return;
    }

    let workShowValid = !required;
    let workShowValue = "";
    let workEditValue = "";
    if (editValid && editValue) {
      const hm = extractHM(editValue);
      workShowValid = true;
      workShowValue = toStringHM(hm, Config.timeDelimiter);
      workEditValue = toStringHM(hm);
    }
    setShowValid(workShowValid);
    setShowValue(workShowValue);
    setEditValue(workEditValue);

    onChange?.(workShowValue);
  };

  useEffect(() => {
    const normalizedValue = value?.trim() ?? "";
    let workShowValid = false;
    const workShowValue = normalizedValue;
    let workEditValue = "";
    try {
      if (!normalizedValue) {
        workShowValid = !required;
        return;
      }
      if (invalidPattern.test(normalizedValue)) {
        return;
      }
      const elements = normalizedValue.replace(/\s/g, "").split(Config.timeDelimiter).reverse();
      if (2 < elements.length) {
        return;
      }
      const hm = extractHM(elements);
      if (!validateHM(hm)) {
        return;
      }
      workShowValid = true;
      workEditValue = toStringHM(hm);
    } finally {
      setShowValid(workShowValid);
      setShowValue(workShowValue);
      setEditValue(workEditValue);
    }
  }, [required, value]);

  if (!show) return null;
  return (
    <TextField
      disabled={disabled ?? false}
      error={error}
      FormHelperTextProps={{ sx: { paddingLeft: "1em" } }}
      fullWidth
      helperText={message}
      InputLabelProps={{ required: false, shrink: true }}
      inputProps={{ maxLength: 4, readOnly: readonly ?? false }}
      onBlur={() => focusHandler(false)}
      onFocus={() => focusHandler(true)}
      onChange={changeHandler}
      required={required}
      value={currentValue}
      variant="standard"
      {...restProps}
    ></TextField>
  );
}
export default memo(TimeField);

// nuxt/components/time-field.vue
<!-- 時間テキストボックス -->

<script setup lang="ts">
defineOptions({
  inheritAttrs: false,
});

interface Props {
  modelValue: string;
  necessary: string;
  readonly?: boolean | undefined;
  disabled?: boolean | undefined;
  errorMessage?: string | undefined;
}
const props = defineProps<Props>();

interface Emits {
  (e: "update:modelValue", value: string): void;
}
const emits = defineEmits<Emits>();

const config = useAppConfig();
const { labels } = useLabel();

const maxHour = Number(config.maxTime.hour) || 0;
const maxMinute = Number(config.maxTime.minute) || 0;
const invalidPattern = new RegExp(String.raw`[^${config.timeDelimiter}\d\s]`);

const show = computed(() => props.necessary !== config.necessary.notNeeded);
const required = computed(() => props.necessary === config.necessary.required);
const message = computed(() => {
  let value = "";
  if (currentValid.value) {
    value = props.errorMessage ? `${config.errorMark}${props.errorMessage}` : "";
  } else {
    const timeNote = `00${config.timeDelimiter}00～${config.maxTime.hour}${config.timeDelimiter}${config.maxTime.minute}`;
    value = required.value ? `${config.errorMark}${labels.value.long.required} ${timeNote}` : timeNote;
  }
  return value;
});

const focus = ref(false);
const editing = computed(() => !props.readonly && !props.disabled && show.value && focus.value);

const showValid = ref(false);
const showValue = ref("");

const editValid = computed(() => (!required.value && !editValue.value) || (!!editValue.value && validateHM(extractHM(editValue.value))));
const editValue = ref("");

const currentValid = computed(() => (editing.value ? editValid.value : showValid.value));
const currentValue = computed({
  get: () => (editing.value ? editValue.value : showValue.value),
  set: (value) => (editValue.value = value),
});

onMounted(() => {
  const stop = watch(
    props,
    (propsValue) => {
      const normalizedValue = propsValue.modelValue.trim();
      showValid.value = false;
      showValue.value = normalizedValue;
      editValue.value = "";
      if (!normalizedValue) {
        showValid.value = !required.value;
        return;
      }
      if (invalidPattern.test(normalizedValue)) {
        return;
      }
      const elements = normalizedValue.replace(/\s/g, "").split(config.timeDelimiter).reverse();
      if (2 < elements.length) {
        return;
      }
      const hm = extractHM(elements);
      if (!validateHM(hm)) {
        return;
      }
      showValid.value = true;
      editValue.value = toStringHM(hm);
    },
    {
      immediate: true,
      deep: false,
    }
  );
  onScopeDispose(stop);
});

const extractHM = (value: string | string[]): [number, number] => {
  const aValue = typeof value === "string" ? value : value.length === 1 ? value[0] : null;
  return aValue ? [Number(aValue.slice(0, -2)) || 0, Number(aValue.slice(-2)) || 0] : [Number(value[1]) || 0, Number(value[0]) || 0];
};

const validateHM = (hm: [number, number]) => 0 <= hm[0] && hm[0] <= maxHour && 0 <= hm[1] && hm[1] <= maxMinute;

const toStringHM = (hm: [number, number], delimiter = "") => `${hm[0].toString().padStart(2, "0")}${delimiter}${hm[1].toString().padStart(2, "0")}`;

const inputHandler = (e: Event) => {
  const element = e.target as HTMLInputElement;
  element.value = element.value.replace(/\D/g, "");
  currentValue.value = element.value;
};

const focusHandler = (value: boolean) => {
  if (props.readonly || props.disabled) {
    return;
  }
  focus.value = value;
  if (value) {
    return;
  }
  if (editValid.value) {
    showValid.value = true;
    showValue.value = "";
    if (editValue.value) {
      const hm = extractHM(editValue.value);
      showValue.value = toStringHM(hm, config.timeDelimiter);
      editValue.value = toStringHM(hm);
    }
  } else {
    showValid.value = !required.value;
    showValue.value = "";
    editValue.value = "";
  }
  emits("update:modelValue", showValue.value);
};
</script>

<template>
  <v-text-field
    maxlength="4"
    v-bind="$attrs"
    v-show="show"
    :disabled="props.disabled"
    :error-messages="message"
    :readonly="props.readonly"
    :value="currentValue"
    @input="inputHandler"
    @update:focused="focusHandler"
  >
    <template #message="{ message:msg }">
      <span style="padding-left: 1em;">{{ msg }}</span>
    </template>
  </v-text-field>
</template>
