// nuxt/pages/attendances/new.vue
<!-- 個別勤怠情報：作成 -->

<script setup lang="ts">
import type { Attendance } from "composables/attendance";

const config = useAppConfig();
const { labels } = useLabel();
const { addFlashMessageKey } = useFlashMessage();
const { create, save } = useAttendance();

const { data: attendance, error } = await create(true);
if (error.value) {
  addFlashMessageIfError(error);
  useRouter().back();
}

const pending = ref(false);

const applyHandler = (value: Attendance) => {
  pending.value = true;
  value.status = config.status.applying;
  save(value, true).then(({ data, error: saveError }) => {
    addFlashMessageIfError(saveError);
    if (!saveError.value && data.value) {
      addFlashMessageKey("successAttendanceApply", "success");
      navigateTo(`/attendances/${data.value.id}`, { replace: true });
    }
    pending.value = false;
  });
};

const saveHandler = (value: Attendance) => {
  pending.value = true;
  value.status = config.status.making;
  save(value, true).then(({ data, error: saveError }) => {
    addFlashMessageIfError(saveError.value);
    if (!saveError.value && data.value) {
      addFlashMessageKey("successAttendanceRegister", "success");
      navigateTo(`/attendances/${data.value.id}/edit`, { replace: true });
    }
    pending.value = false;
  });
};
</script>

<template>
  <h1>{{ labels.long.new }}</h1>
  <attendance-detail action="new" v-if="attendance" :attendance="attendance" :pending="pending">
    <template #actions="{ valid, value }">
      <v-col class="text-left">
        <v-btn size="x-large" :disabled="pending || !valid" :loading="pending" @click="applyHandler(value)">{{ labels.long.apply }}</v-btn>
      </v-col>
      <v-col class="text-center">
        <v-btn size="x-large" :disabled="pending" :loading="pending" @click="saveHandler(value)">{{ labels.long.save }}</v-btn>
      </v-col>
    </template>
  </attendance-detail>
</template>

// next/src/app/attendances/new/page.tsx
"use client";

import { useAtomValue } from "jotai";
import { useCallback, useEffect, useMemo, useState } from "react";

import { Attendance } from "@/api/attendance";
import Loading from "@/app/loading";
import Config from "@/app.config";
import DetailForm from "@/components/attendance/parts/detail-form";
import { createActionFunction } from "@/components/attendance/parts/detail-form-action";
import { Subtitle } from "@/components/attendance/subtitle";
import { useAttendance } from "@/composables/attendance";
import { addFlashMessage } from "@/composables/flash-message";
import { labelsAtom } from "@/composables/label";
import { messagesAtom } from "@/composables/message";
import { useRouter } from "@/composables/router";

/** 勤怠情報新規作成ページ（/attendances/new） */
export default function NewAttendance() {
  const router = useRouter();
  const labels = useAtomValue(labelsAtom);
  const messages = useAtomValue(messagesAtom);

  const { create, save } = useAttendance();
  const [attendance, setAttendance] = useState<Attendance | undefined>(undefined);
  const [pending, setPengind] = useState(false);

  const register = useCallback(
    (attendance: Attendance, message: string) => {
      setPengind(true);
      save(attendance).then(
        (data) => {
          setPengind(false);
          addFlashMessage(message, "success");
          const action = data.status === Config.status.making ? "/edit" : "";
          router.replace(`/attendances/${data.id}${action}`);
        },
        (error) => {
          setPengind(false);
          addFlashMessage(error.message, "error");
        }
      );
    },
    [router, save]
  );

  const applyHandler = useCallback(
    (attendance: Attendance) => () => {
      attendance.status = Config.status.applying;
      register(attendance, messages.successAttendanceApply!);
    },
    [messages.successAttendanceApply, register]
  );

  const saveHandler = useCallback(
    (attendance: Attendance) => () => {
      attendance.status = Config.status.making;
      register(attendance, messages.successAttendanceRegister!);
    },
    [messages.successAttendanceRegister, register]
  );

  const backHandler = useCallback(() => router.back(), [router]);

  const createActionElement = useMemo(
    () =>
      createActionFunction(
        { label: labels.long.apply!, onClick: applyHandler, valid: true },
        { label: labels.long.save!, onClick: saveHandler, valid: false },
        { label: labels.long.back!, onClick: backHandler },
        pending
      ),
    [applyHandler, backHandler, labels.long.apply, labels.long.back, labels.long.save, pending, saveHandler]
  );

  useEffect(() => {
    create().then(
      (data) => setAttendance(data),
      (error) => {
        addFlashMessage(error.message, "error");
        router.replace("/");
      }
    );
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <>
      <Subtitle>{labels.long.new}</Subtitle>
      {attendance ? <DetailForm createActionElement={createActionElement} value={attendance} /> : <Loading />}
    </>
  );
}
